### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by rhythmize** [lukauskas/dtwco#3]
can't import in win64 platform.....following error...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\mlpy__init__.py", line 6, in <module>
    from . import gsl
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by areibman** [comment]
Also have this error. Huge problem.

I came up with a workaround solution though. Install mlpy from this website using Pip http://www.lfd.uci.edu/~gohlke/pythonlibs/

Hope that helps.

**Comment by lukauskas** [comment]
Closing this down as this looks like `mlpy` issue.
This project is no longer affiliated with it, as per latest PR. 

Consult [mlpy docs](http://mlpy.sourceforge.net/) for information about it, though that project is essentially dead. My personal recommendation is to check if [scikit-learn](http://scikit-learn.org/) have the desired functionality.
